### ISSUE TITLE
Can't save my dynamically added data!!

### ISSUE THREAD

**Issue by Riad-Hossain** [adityapurwa/tabullet#1]
Hi Aditya,
tabullet.js is just awesome but now i am facing a problem with this. when i refresh my table it back with  its default values. as a result  i lose my data that  was added dynamically. how to solve this problem??

**Comment by adityapurwa** [comment]
Hi @Riad-Hossain, Tabullet is **not responsible for persisting the data** into database or any other storage. To  save dynamically added data, the data collected by Tabullet must be saved into database, and then loaded from the database on refresh.

If you do not use a database, you can use `localStorage` API to store the data. Here is an example on how to do it using `localStorage` API based on Tabullet's example.

      $(function () {
            var source = [
                {id: 1, name: "Aditya Purwa", level: "Admin"},
                {id: 2, name: "Aditya Avaga", level: "Manager"},
                {id: 101, name: "Aditya Myria", level: "User"},
                {id: 102, name: "Lucent Serentia", level: "LOD"},
                {id: 103, name: "Hayden Bapalthiel", level: "King"},
            ];

            var savedSource = localStorage.getItem("mydata");
            if (savedSource) {
                source = JSON.parse(savedSource);
            }

            function resetTabullet() {
                $("#table").tabullet({
                    data: source,
                    action: function (mode, data) {
                        console.dir(mode);
                        console.dir(data);
                        if (mode === 'save') {
                            source.push({
                                name: data.name,
                                level: data.level
                            });
                        }
                        if (mode === 'edit') {
                            for (var i = 0; i < source.length; i++) {
                                if (source[i].id == data.id) {
                                    source[i] = {
                                        name: data.name,
                                        level: data.level,
                                        id: data.id
                                    }
                                }
                            }
                        }
                        if (mode == 'delete') {
                            for (var i = 0; i < source.length; i++) {
                                if (source[i].id == data) {
                                    source.splice(i, 1);
                                    break;
                                }
                            }
                        }

                        resetTabullet();
                    }
                });
                localStorage.setItem("mydata", JSON.stringify(source));
            }

            resetTabullet();
        });
